image:
  file: .gitpod.Dockerfile

tasks:
    - name: Install Opencv Build
      command: sh ./opencv_install.sh
      openMode: split-right  
  
vscode:
  extensions:
      - vscjava.vscode-java-pack